<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit97ecade1c678b4823924cb05fb68dc7d
{
    public static $prefixLengthsPsr4 = array (
        'J' =>
        array (
            'Jankx\\Extensions\\CustomLoginPage\\' => 33,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jankx\\Extensions\\CustomLoginPage\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit97ecade1c678b4823924cb05fb68dc7d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit97ecade1c678b4823924cb05fb68dc7d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit97ecade1c678b4823924cb05fb68dc7d::$classMap;

        }, null, ClassLoader::class);
    }
}
